version: '3.9'
services:
  postgres:
    image: postgres:9.6-alpine
    restart: always
    hostname: kong-database
    container_name: kong-database
    environment: 
      POSTGRES_USER: "kong"
      POSTGRES_DB: "kong"
      POSTGRES_PASSWORD: "kongkong@987"
    ports:
      - "5432:5432"
  kong-bootstrap:
    image: kong:2.5.0-alpine
    hostname: kong-bootstrap
    container_name: kong-bootstrap
    depends_on:
      - postgres
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-database"
      KONG_PG_DATABASE: "kong"
      KONG_PG_USER: "kong"
      KONG_PG_PASSWORD: "kongkong@987"
    command: "kong migrations bootstrap"
    restart: 'on-failure'
  kong:
    image: kong:2.5.0-alpine
    restart: always
    hostname: kong
    container_name: kong
    depends_on: 
      - kong-bootstrap
    environment: 
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "kong-database"
      KONG_PG_USER: "kong"
      KONG_PG_PASSWORD: "kongkong@987"
      KONG_PROXY_ACCESS_LOG: '/dev/stdout'
      KONG_ADMIN_ACCESS_LOG: '/dev/stdout'
      KONG_PROXY_ERROR_LOG: '/dev/stdout'
      KONG_ADMIN_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_LISTEN: "0.0.0.0:9001, 0.0.0.0:8444 ssl"
    command: "kong start"
    ports:
      - "8009:8009"
      - "8443:8443"
      - "9001:9001"
      - "8444:8444"
networks:
  default:
    name: kong-net